# Awards {#sec-art-KAF5NVBG}

## Award Election Procedure {#sec-art-WWI418WD}

1. For each award that the chapter gives:
   a. Nominations will be opened prior to voting.
   a. Voting will take place after nominations have been closed.
   a. Voting will be done by show of hands.
   a. A brother may vote *No Confidence* if he is not satisfied with any of the nominees.
   a. There will be no discussion between nominations and voting.
   a. If there are less than 4 nominees, the nominee will be elected to receive the award by {{< var glossary.plurality >}} of voting members present.
   a. Otherwise, there will be a runoff (decided by {{< var glossary.plurality >}}) between the three nominees that received the highest counts of votes.
   a. If a {{< var glossary.plurality >}} of votes cast are *No Confidence*, voting will end and no award will be given.

## Specified Awards {#sec-art-GZYYZN72}

1. Brotherhood Award:
   a. Will be awarded to a current brother who best exemplifies the ideals of Theta Chi Fraternity. b. Will be awarded before the end of the Spring Semester.

1. Alumni Service Award:
   a. Will be given to the alumnus who has done the most for the currently active chapter.
   a. Will be given annually at OX Roast.
   a. A plaque will be maintained by the Alumni Relations Committee Chairman that includes the names of the Alumni who have won the award.

1. Dream Girl Award:
   a. Will be bestowed upon the woman associated with Beta Nu Chapter who has done the most for the presently active chapter.
   a. Will be elected by the second regularly scheduled chapter meeting after initiation during the spring semester.
   a. Voting will be done by {{< var glossary.ballot >}} in direct exception to @sec-art-WWI418WD, Item 1b.

1. Certificate of Appreciation:
   a. May be presented to any person who has demonstrated service of extraordinary care and effort to the chapter.\
   a. Will consist of a certificate of appropriate construction and suitable wording which describes the service for which the certificate is being presented.
   a. Any brother eligible to vote may, at any chapter meeting, nominate any person.
   a. Discussion will be allowed for this award in direct exception to @sec-art-WWI418WD, Item 1c.
   a. A nominee must receive a {{< var glossary.supermajority >}} vote to receive this award in direct exception to @sec-art-WWI418WD, Item 1b.
   a. The chapter may give out any number of this award.

1. The Theta Chi Scholar Award
   a. May be bestowed on up to three active brothers each semester for their achievements at the university, whether that may be by coursework, research, work, teaching experience, athletics, extracurricular activities, anything else that makes him an outstanding member of the {{< var acronym.cwru >}} community, brother of Theta Chi, and citizen of the world. No brother may receive this award two semesters of CWRU enrollment in a row.
   a. Will consist of a certificate of appropriate construction and suitable wording which describes the accomplishments for which the certificate is being presented.
   a. The giving procedure, in direct exception to @sec-art-WWI418WD will be as follows:
      i. Nominations will be opened for no shorter than two weeks. Any brother eligible to vote may, at any time when nominations are open, nominate any active member of the fraternity. To do so requires a second.
      i. Any brother who is nominated may accept the nomination before nominations close by way of informing the Scholarship Chair of his acceptance and explaining why he thinks he is an exemplar of on-campus achievement among the members of the fraternity.
      i. The Standards Board will discuss each nominee. In this discussion, the consideration will be of the ideals of the award, listed in Point A, with the stipulation that this award is meant to be open to brothers who are a role model in any way listed above – one does not need to be exemplary in every area to still be an example. No member of the Standards Board may contribute to discussion regarding their own scholarship if they themselves have been nominated, but they are welcome to discuss the award in context of other brothers. Although the Scholarship Chair and President may be aware of an individual brother’s {{< var acronyms.gpa >}}, they are not allowed to disclose this information unless the brother in question has provided it with their application.
      i. The Standards Board will decide, by majority vote, at most three applicants who are deserving of the title of Theta Chi Scholar for the semester. 
      i. These brothers will be announced at a suitable time before the end of the semester. For the spring semester, this should be at the Scholarship Dinner.


1. The chapter may give out any other awards subject to the procedures defined in @sec-art-WWI418WD.
