# Voting {#sec-art-D6BOCVLV}

## Voting Overview {#sec-art-GW6C9D29}

1. All brothers eligible to vote must vote.
1. Only active brothers who are not on {{< var glossary.probation >}} or {{< var glossary.financial-probation >}} are eligible to vote.
1. Brothers must be present for all of the discussion on a motion in order to be eligible to vote on that motion.
1. A brother not required to pay local dues is ineligible to vote.
1. Unless specified in @sec-art-N8IIFY4C, or explicitly voted on by {{< var glossary.simple-majority >}}, the method of voting will be by a counted show of hands.

## Procedure {#sec-art-N8IIFY4C}

1. The following votes will be performed by ballot:
   a. New Members for Initiation
   b. Officer Elections
   c. To overturn an Executive Council ({{< var acronyms.ec >}}) Interpretation of the bylaws (@sec-art-EXPT5HOU)
   d. At a suspension trial
   e. To retain a candidate who was not initiated the previous semester

1. {{< var glossary.ballot >}}ing
   a. The Second Guard and the Chaplain will collect and count the {{< var glossary.ballot >}}s.
   b. The chaplain will confirm the count and repeat the results to the presiding officer.
   c. No brother may count the {{< var glossary.ballot >}}s for a matter related to himself.
   d. In the case of absence, conflict of interest, or at the discretion of the chair, the chair may appoint a brother to collect and count the {{< var glossary.ballot >}}s.

1. New Members for Initiation
   a. {{< var glossary.ballot >}}ing on New Members for Initiation will be in accordance with the International Bylaws ({{< var acronyms.ibl >}}) of Theta Chi Fraternity, Article VI, Section 4, paragraph d.
   b. New Members must be approved by a ¾ vote of eligible voting members of the active chapter to be initiated.

1. Officer Elections
   a. Officers will be elected by {{< var glossary.simple-majority >}} vote.
   b. In the case that no nominee receives a {{< var glossary.simple-majority >}}, there will immediately be another vote between all candidates who received the two highest counts of votes.\
   c. Nominations for president and treasurer must be a week before nominations for the other positions in order to make time for {{< var acronyms.cab >}} interviews.
