# Standards Board

## Preface

1. This section's purpose is to summarize the Standards Board Hearing Procedures in the International Bylaws ({{< var acronyms.ibl >}}), as well as describing the procedure for Academic Review. For more detailed procedures on Standards Board Trials, refer to {{< var acronyms.ibl >}} Article V, Section 22.

## Purpose

1. To judge infractions of the bylaws and standards of the chapter as well as all other laws and rules brothers must adhere to as defined in {{< var acronyms.ibl >}} Article V, Section 22(a).
1. To run Academic Reviews.

## Membership

1. The composition of Standards Board includes the Vice President as the chair, the Chaplain, and three additional at-large members ({{< var acronyms.ibl >}} Article V, Section 22(b)).
1. The terms of office of the members of Standards Board are outlined in the {{< var acronyms.ibl >}} Article V, Section 22(c). 3. Vacancies should be filled according to {{< var acronyms.ibl >}} Article V, Section 22(g).

## Voting

1. Unless otherwise specified, votes of the board are by {{< var glossary.simple-majority >}}.
1. {{< var glossary.quorum >}} of the board consists of ⅘ of its members.
1. The voting members of the board are the Chaplain and the three at-large members ({{< var acronyms.ibl >}} Article V, Section 22(i)).
1. The Vice President may only vote in the case of a tie ({{< var acronyms.ibl >}} Article V, Section 22(i)).

## At-Large Member Removal

1. If, at any time, an at-large member becomes ineligible to hold office or is elected to an Executive Council ({{< var acronyms.ec >}}) position, that at-large member is immediately removed from office.
1. Any At-Large Member may be removed for the following reasons:
   a. Failure to perform their duties, including unexcused absence from more than one board meeting per semester.
   a. Failure to maintain confidentiality of all proceedings of the board.\
   a. Conduct unbecoming of an at-large member or which negatively affects the credibility of the board.
   a. At-large members can only be removed by an {{< var glossary.absolute-supermajority >}} vote of the active chapter ({{< var acronyms.ibl >}} Article V, Section 22(e)).

## Accusation Procedure

1. All accusations must be submitted in writing to the Vice President within one month of the most recent violation.
   a. Each accusation must be as detailed as possible including at least the clause of the local bylaws that was violated.
   a. Each accusation must be submitted within one month of the violation.

1. Upon receiving the Accusation, the Vice President will decide whether or not a hearing will take place ({{< var acronyms.ibl >}} Article V, Section 22(j)(2)).
   a. The Vice President may request the First Guard and Second Guard to advise him as to whether or not there should be a hearing.
   a. If the Vice President decides that there will not be a hearing, proceedings will end and no hearing will be held.

1. If there is to be a hearing, the Vice President will then decide whether the hearing will be a Standards Board Hearing or a Chapter Hearing.
   a. The Vice President may not request advice from anyone other than a {{< var glossary.chapter-advisor >}} on this matter.
   a. If the accuser and/or accused disagree with the decision of which type of hearing the accusations are brought to, they may appeal the decision.
   a. The appeal will be brought exclusively to the voting members of Standards Board to vote on whether the appeal is valid.
      i. If the appeal is found to be valid, the Vice President's decision on the type of hearing will be overruled.

1. The Vice President will then inform the accuser of the validity of the accusation.

1. If the accusation is found to be without merit, proceedings will end and no hearing will be held.

1. If the Vice President decides there will be a hearing, the Vice President will provide written notification to the accused.
   a. The notification must be given within forty-eight hours of receipt of the accusation.
   a. The notification must include:
      i. The accusations with enough detail to allow the accused to prepare a defense.
      i. The type of hearing taking place.

1. Upon receiving the notification, the accused has twenty-four hours to submit a plea in writing to the Vice President.
   a. The possible pleas are {{< var glossary.responsible-plea >}}, {{< var glossary.not-responsible-plea >}}, and {{< var glossary.no-contest-plea >}}.\
   a. If a plea is not received within the twenty-four hours specified above, a {{< var glossary.no-contest-plea >}} will be entered.

1. After a plea is entered, the Vice President will schedule a time and place for the hearing.
   a. The hearing shall occur between 1 and 3 weeks after a plea is entered.
   a. The Vice president will notify the accused and accuser of the time, date, and location of the hearing.
      i. If a Standards Board Hearing is to be held, the Vice President will also notify the Chaplain and the at-large members of Standards Board of the time, date, and location of the hearing.
      i. If a Chapter Hearing is to be held, the Vice President will inform all non-suspended brothers of the active chapter and the Chapter Advisory Board ({{< var acronyms.cab >}}) of the time, date and location of the hearing.

1. The Vice President will inform {{< var acronyms.ec >}} of the accusation, the accused, and the nature of the complaint at the next {{< var acronyms.ec >}} meeting.

1. Recusal
   a. Members of the board will recuse themselves from the hearing if they feel a conflict of interest exists or they are the accused.
   a. Members of the board may be recused by {{< var glossary.simple-majority >}} vote of the remaining board. The accused, accuser, or a member of the board may call for such a vote.
   a. Members of the Standards Board may recuse themselves. Members of Standards Board, the accused, or accuser may call for a vote to recuse any member of Standards Boardup to the beginning of the trial.
   a. Vacancies due to recusal should be filled in accordance with {{< var acronyms.ibl >}} Article V, Section 22(j)(9)(v) or (vi), as they apply to the situation.

1. If the type of hearing was determined to be a Chapter Hearing, proceed with Article XIII, Section E.

## Hearing Preparation

1. Evidence and a statement by the anonymous accuser will be distributed by the Vice President to all members of the Standards Board between twenty-four and forty-eight hours before the hearing date and time.
1. Witnesses may volunteer to speak on behalf of or against the charges.
   a. The witnesses may volunteer by giving a written message to the Vice President stating their intent to participate and their stance at least three hours before the trial.
1. Witnesses will be advised by the Vice President that they are not to discuss the hearing or the accusation outside of the hearing.
1. Witnesses must remain outside the room until called by the Vice President and leave when dismissed.
1. The dress at the hearing will be informal.
1. The Vice President will call the hearing to order and ask all but the directly related participants to leave the room. The directly related participants are the members of Standards Board as defined in Article XII, Section C, Item 2 and the accused.

## Hearing Method

1. The Vice President reads aloud the charges and ensures that the accused understands the charges.

1. The accused may give an opening statement with a time limit as voted on by the voting members of Standards Board.

1. The accused may then be asked questions by the members of Standards Board and the {{< var glossary.chapter-advisor >}} (if he is present) with a time limit as voted on by the voting members of Standards Board.

1. All witnesses will be brought into the room by the Vice President.

1. Witnesses that wish to speak for the charges will be chosen in an order decided by the Vice President to give a statement. The accused, {{< var glossary.chapter-advisor >}} (if he is present), and members of the Standards Board will ask questions of the witness(es) with a time limit as voted on by the voting members of Standards Board.

1. Witnesses that wish to speak against the charges will be chosen in an order decided by the Vice President to give a statement. The accused, {{< var glossary.chapter-advisor >}} (if he is present), and members of the Standards Board will ask questions of the witness(es) with a time limit as voted on by the voting members of Standards Board.

1. All witnesses will be excused by the Vice President.

1. The accused may give a closing statement with a time limit as voted on by the voting members of Standards Board.

1. The Vice President will excuse the accused from the hearing.

1. The voting members of Standards Board will determine if the accused is {{< var glossary.responsible >}} or {{< var glossary.not-responsible >}} for the accusations brought forth against him.
   a. The Vice President and {{< var glossary.chapter-advisor >}} (if one is present) may offer input to this discussion but may not vote in the final decision unless it is a tie, in which case the Vice President will vote to break the tie.
   a. Any member of Standards Board may recall any witnesses or the accused, if further questions arise. This may be done once per witness. To recall a witness more than once requires a unanimous vote of the voting members of Standards Board.

1. The voting members of Standards Board will then determine appropriate sanctions, if any.
   a. Past judicial history of the accused and sanctions given for similar accusations in the past (as found in Appendix B) may be considered.
   a. The Vice President and {{< var glossary.chapter-advisor >}} (if one is present) may offer input to this discussion but may not vote in the final decision unless it is a tie, in which case the Vice President will vote to break the tie.
   a. The voting members of Standards Board will vote on all sanctions, one at a time.
   a. If the sanction being voted on is temporary suspension for any duration of time, the vote must be unanimous in the affirmative in order to succeed.

1. After the sanctions have been determined, the Vice President will readmit the accused back to the hearing and will announce the sanctions given, if any.

1. The Vice President will then inform the accused of the appeal process.

1. The Vice President will then adjourn the hearing.

## Sanctions

1. The board may issue sanctions within its limited scope. The following are examples of possible sanctions:
   a. Community Service
   a. Cost of repairs
   a. Fines
   a. House Service
   a. Letter of Apology
   a. Removal from an Appointed Position
   a. Recommendation for suspension
   a. Temporary Suspension

1. The Vice President will ensure the completion of sanctions.
   a. If the sanctions are not completed, the Vice President will bring the brother up for standards.

## Appeals

1. The accused may appeal a decision of Standards Board.
   a. Appeals must be submitted within 7 days after receiving written notification of the results of the hearing.
   a. If an appeal is made, the confidentiality of the hearing is waived starting at the next regularly scheduled chapter meeting at which {{< var glossary.quorum >}} is present.

1. A decision can only be appealed for the following reasons:
   a. The procedure for the hearing was not followed.
   a. New information is discovered that wasn't available at the time of hearing.
   a. The sanction is inappropriate.

1. The appeal will be presented in writing to the Vice President and will state the grounds for the appeal.

1. Appeals will be presented to the active chapter at the next regularly scheduled chapter meeting at which {{< var glossary.quorum >}} is present.

1. At the next chapter meeting, the appellant will explain the reason for the appeal. The Vice President will then explain the board's decision. Following the statements, the accused will leave the room and a discussion will take place. The chapter may overturn the sanctions with a ¾ vote in the affirmative of all chapter members present and eligible to vote.

1. If the decision is overturned, the chapter may give new sanctions by {{< var glossary.simple-majority >}} vote.

1. After the chapter has voted, the accused brother will be readmitted to the meeting by the Vice President and will be informed of the decision by the Vice President.

1. An appeal may be made only once.

## Academic Review

1. An Academic Review shall be held whenever the Scholarship Chair requests an Academic Review in accordance with the duties of their office.

1. An Academic Review is not a Standards Board Hearing.

1. An Academic Review shall be carried out by the Scholarship Chair and the members of Standards Board.

1. A {{< var glossary.quorum >}} of Standards Board is required to hold an Academic Review.

1. Attendance of an Academic Review is mandatory for all members of Standards Board and the Scholarship Chair.

1. A member of Standards Board may be recused from an Academic Review under the following circumstances:
   a. Members of the board for whom the Scholarship Chair is requesting a suspension trial will recuse themselves.
   a. Members of Standards Board will recuse themselves if they feel a conflict of interest exists.
   a. Members of Standards Board may be recused by a {{< var glossary.simple-majority >}} vote of the remaining members of Standards Board. The brother under review, the Scholarship Chair, or a member of Standards Board may call for such a vote.

1. Process of an Academic Review
   
   a. Scheduling:
      i. The Vice President will schedule Academic Reviews.
      i. All Academic Reviews for a semester shall be held at the beginning of the semester at the discretion of the Vice President.
      i. Members of Standards Board of whom the Scholarship Chair has requested an Academic Review will have their Academic Reviews completed before the Academic Reviews of brothers not on Standards Board. If the Scholarship Chair has requested an Academic Review for the Vice President, the Academic Review for the Vice President will happen first.
      i. The Vice President will inform the board, Scholarship Chair, and brothers under review of the day's schedule within three days of the Scholarship Chair requesting academic suspensions.
   
   b. Preparation:
      i. The brother under review is not required to {{< var glossary.attend >}}.
      i. Both the brother under review and the Scholarship Chair may provide witnesses and any form of relevant documents, including written statements. If either the brother under review or the Scholarship Chair cannot {{< var glossary.attend >}} the review, any such documents must be sent to the Vice President along with an order of any witnesses to be called.
      i. The Vice President will call the meeting to order and ask all but unrecused members of the board, the Scholarship Chair, and the brother under review to leave the room.
   
   c. Method:
      i. The Scholarship Chair and brother under review may give an opening statement, in that order.
      i. The Scholarship Chair may then be asked questions by the brother under review and the board.
      i. The brother under review may then be asked questions by the Scholarship Chair and the board.
      i. The Scholarship Chair and then the brother under review may then present any witnesses or documents. If they are not present, the provided witnesses and documents will be presented in the provided order. After each witness gives a statement, the Scholarship Chair, brother under review, and members of Standards Board may ask questions of the witness. Documents will remain with the Vice President until the conclusion of the review.
      i. The Scholarship Chair and brother under review may give closing statements in that order. vi. The Vice President will excuse the Scholarship Chair and brother under review.
      i. The members of Standards Board will then deliberate. The members of Standards Board may consult any documents and recall any witnesses, the Scholarship Chair, or the brother under review if further questions arise.
      i. The voting members of Standards Board will vote to either recommend the brother under review for suspension, or to not recommend the brother under review for suspension.
      i. The Vice President will recall the Scholarship Chair and the brother under review and inform them of the decision made by Standards Board.
      i. If Standards Board voted to recommend the brother under review for suspension, the Vice President will immediately inform the President of the decision made by Standards Board and request a suspension trial for the brother under review.

1. In the event that Standards Board does not recommend the brother under review for suspension, the proceedings of the review will remain confidential.

1. In the event that the board recommends the brother under review for suspension the proceedings of the review will not be confidential. Any statements by the Scholarship Chair, brother under review, or witnesses, the content of any presented documents, and the nature of the deliberation done by Standards Board may be requested and discussed during the associated suspension trial.
