# Chapter Meetings {#sec-art-R50R4PX6}

## Time {#sec-art-386EGZU4}

1. The active chapter will meet once per week while school is in session, as required by International Bylaws ({{< var acronyms.ibl >}}) Article V, Section 7, Part A.
1. The default time for a chapter meeting will be Sunday at 6:30 PM unless legislated otherwise.

## Excuses {#sec-art-H23EB4B2}

1. Excuses for chapter meetings must be submitted in writing to the Secretary according to the method and time specified by the Excuse Plan.
1. Excuses must be approved by a {{< var glossary.simple-majority >}} vote of Executive Council ({{< var acronyms.ec >}}).
1. Failure to {{< var glossary.attend >}} a chapter meeting without an approved excuse (in accordance with @sec-art-H23EB4B2, Item 1) will count as an unexcused absence.

## Absences {#sec-art-BUK07FVL}

1. A brother who has three unexcused absences in a row must be brought up for standards by the Secretary in accordance with Article V, Section 2, Item j.1 of the {{< var acronym.ibl >}}.
1. A brother who has three unexcused absences throughout the semester will be {{< var glossary.staggard >}}.
1. A brother who has four unexcused absences throughout the semester will be placed on {{< var glossary.probation >}} until the end of the semester.
1. A brother who has seven unexcused absences throughout the semester will be brought up for standards by the Secretary with the possibility of suspension.

## Rules and Regulations {#sec-art-8XE7XCGC}

1. All officer reports and communications must be submitted in writing to the Secretary prior to a chapter meeting at a time decided by the Secretary. Emergency reports or communications may be given at the discretion of the presiding officer.
1. No one will leave any chapter meeting unless excused by the presiding officer.
1. Any member whose conduct is unbecoming of a brother may be asked to leave the meeting by the presiding officer.
1. The First Guard will determine and enforce proper dress code at chapter meetings.
1. At the discretion of the First Guard, entrance to chapter meetings will be conducted according to Ritual.
1. No guests will be permitted on the first floor or basement of the house during a chapter meeting or the preparation thereof unless permitted by the chair.
1. There will be no food or drink, with the exception of water in a resealable container, at any chapter meeting, unless the First Guard declares otherwise.
1. Motions that call for a vote require a {{< var glossary.simple-majority >}} in order to be passed, unless the creator of the motion specifies otherwise.
