# Officer Selection and Duties {#sec-art-F8LOE4WJ}

## Terms of Office {#sec-art-3MIFLS7V}

1. All elected offices will have yearly terms.
1. The President will appoint all appointed officers subject to a {{< var glossary.simple-majority >}} vote of the chapter.
1. Appointed positions will have semesterly terms except for Alumni Relations Chair, Community Standards Chair, and Standards Board At-Large Member.
1. The Recruitment Chair and Public Relations Chair will serve from the end of the first {{< var glossary.rush-period >}} after election or appointment through the first {{< var glossary.rush-period >}} after the election or appointment of a new officer.

## Nominations {#sec-art-NUXDQ4I0}

1. Nominations will be opened at least one week before elections.
1. All members, in order to be eligible for nomination, must be in good standing with the University and the International Fraternity and must not be on {{< var glossary.financial-probation >}}.

## Elections {#sec-art-3AOCUCRJ}

1. Officers will be elected in accordance with the International Bylaws ({{< var acronyms.ibl >}}) Article V, Section 3.

1. Nominations must be closed in order to elect an officer.

1. For each elected position the election will proceed as such:
   a. For each candidate:
      i. Candidates will be allowed speeches following these rules:
         1. Other candidates will leave the room.
         1. Candidates will be allowed not less than three minutes to speak.
      i. The chapter will be allowed to ask the candidate questions following these rules:
         1. The chapter will be allowed not less than two minutes to question.
         1. Any time not used by a candidate for his speech will be allowed for questions.
   a. The chapter will discuss the candidates subject to the following rules:
      i. All candidates will leave the room.
      i. The chapter will be allowed not less than five minutes to discuss.
      i. If the candidate is elected by white {{< var glossary.ballot >}}, this section does not apply.\
   a. Pledges will be allowed to vote in the election in direct exception to the above @sec-art-GW6C9D29, Item 2.

1. If an elected position should become vacant:
   a. The President will immediately appoint an interim officer, preferably a brother who has held the office before.
   a. Nominations will immediately open for the vacant position, and will close at the next regularly scheduled chapter meeting.
   a. The week following the opening of nominations, elections will proceed as defined above in @sec-art-3AOCUCRJ.

## Elected Officers and Their Duties {#sec-art-YZW2AQAI}

1. President
   a. Performs all duties stated in the {{< var acronyms.ibl >}} Article V, Section 6, paragraph a.
   a. Serves as a liaison between the chapter and the community.
   a. {{< var glossary.attend >}}s all Interfraternity Congress ({{< var acronyms.ifc >}}) and Greek Life Office functions expected of the President.
   a. {{< var glossary.attend >}}s all Chapter Advisory Board ({{< var acronyms.cab >}}) meetings.
   a. {{< var glossary.responsible >}} for the overall completion of {{< var glossary.community-standards >}}.
   a. A candidate for the position of President must be interviewed by {{< var acronyms.cab >}} prior to the election. A {{< var glossary.simple-majority >}} vote of {{< var acronyms.cab >}} may veto that candidate. This veto can be overruled by a {{< var glossary.supermajority >}} vote of the chapter. Failure for {{< var acronyms.cab >}} to meet with a candidate prior to elections will be interpreted as {{< var acronyms.cab >}} waiving their right to interview the candidate.
   a. Serves as a member of Executive Council ({{< var acronyms.ec >}}).
   a. Must live in the house.

1. Vice President
   a. Performs all duties stated in the {{< var acronyms.ibl >}} Article V, Section 6, paragraph b.
   a. Serves as Parliamentarian for the chapter and is {{< var glossary.responsible >}} for all committees.
   a. Maintains the chapter's local bylaws.
   a. Ensures legislation records are up to date.
   a. Adds all permanent legislation to the appropriate appendix as outlined in @sec-art-Q8OV40FK.
   a. Adds {{< var acronyms.ec >}} Interpretations to the Appendices.
   a. Appoints active members to committees at the beginning of each semester.
   a. Assigns living space as outlined in @sec-art-C89656BJ.
   a. Fills out Greek Life and International Headquarters ({{< var acronyms.ihq >}}) awards that are due in their term.
   a. Serves as chair of the Bylaw Revision Committee as outlined in @sec-art-YOSPIQLS.
   a. Serves as chair of {{< var acronyms.ec >}} and represents it to the chapter.
   a. Serves as chair of the Committee Chair Committee ({{< var acronyms.ccc >}}).\
   a. Serves as chair of Standards Board.
   a. May make Ad Hoc Committees at their discretion as defined in @sec-art-VI2T9PVL, Item 3a. o. Must live in the house.

1. Vice President of Health and Safety
   a. Performs all duties stated in the {{< var acronyms.ibl >}} Article V, Section 6, paragraph c.
   a. Plans and oversees a yearly community outreach event regarding health and safety.
   a. Serves as a liaison between the chapter and community health services.
   a. Organizes events on 5 topics, 2 of which are available to the greater public, on Health and Safety for the chapter per academic year in accordance with the five areas of Sacred Purpose.
   a. Maintains house medical kit.
   a. Serves as a member of {{< var acronyms.ec >}}.
   a. Serves as chair of the Health and Safety Committee.
   a. Must live in the house.

1. Secretary
   a. Performs all duties stated in the {{< var acronyms.ibl >}} Article V, Section 6, paragraph d.
   a. Records attendance and enforces the standards for attendance in @sec-art-BUK07FVL.
   a. Serves as Secretary of {{< var acronyms.ec >}}.
   a. Collects all legislation, Bylaw amendments, and Officer Reports.
   a. Sets the agenda for chapter meetings according to the {{< var acronyms.ibl >}} Article V, Section 8, paragraph d.
   a. Maintains the mailbox and mail closet.
   a. Will create a contact list for the chapter which includes contact information of brothers advisors, Greek Life, and emergency services.
   a. Handles registration of Pledges, requests for initiation, and the recording of new initiates.
   a. Fills out Greek Life and International Headquarters (IHQ) awards that are due in their term.
   a. Releases a weekly TWIOX (This Week in Theta Chi) newsletter to the alumni mailing list

1. Treasurer
   a. Performs all duties stated in the {{< var acronyms.ibl >}} Article V, Section 6, paragraph e.
   a. Is accountable to the Alumni Corporation.
   a. Collects all feeds, dues, and fines.
   a. Records all transactions made by the chapter.
   a. Will provide a written report at the request of any brother which includes all payments paid out, all monies received, current bank account balances, and budget updates.
   a. Keeps private all individual account balances except from the brother whose account it is and {{< var acronyms.ec >}}.
   a. Issues enumerated bills for all brothers and New Members at least three times a semester unless otherwise decided by the chapter.
   a. Announces the names of all members on {{< var glossary.financial-probation >}} at each chapter meeting during the Treasurer's Report or before any vote, whichever occurs first.
   a. Will create a budget following the process outlined in @sec-art-GD7C1K2U.\
   a. Ensures compliance with the General Rules for chapter finances outlined in @sec-art-SKY8T9UM.
   a. Will propose a housing contract to the chapter by the last chapter meeting of each semester with a final version to be approved at the first chapter meeting of the next semester.
   a. Will ensure that all brothers living in the house have signed a housing contract by the second chapter meeting of each semester.
   a. Maintains an emergency fund of no less than $3000 and can withdraw money from the fund only with the authorization of two of the three highest officers.
   a. Will meet with the Alumni Financial Advisor at least twice each semester.
   a. Will file taxes at least two weeks before the filing deadline each year.
   a. Will ensure that taxes will be reviewed by the {{< var acronyms.cab >}} financial advisor, alumni housing corporation financial advisor, and {{< var acronyms.ec >}} no later than one month before the filing deadline.
   a. Will send taxes by certified mail, and will distribute this certification to the {{< var acronyms.cab >}} financial advisor, alumni housing corporation financial advisor, and {{< var acronyms.ec >}}.
   a. Will retain a physical and electronic backup of financial records for no fewer than five years.
   a. Maintain a changelog of the budget.
   a. Give a monthly financial report to the chapter and deliver the report to {{< var acronyms.cab >}}.
   a. The Treasurer cannot be elected or appointed to a position which has permission to spend from the budget.
   a. Cannot be elected to another position during their term.
   a. A candidate for the position of Treasurer must be interviewed by the {{< var acronyms.cab >}} prior to the election. A {{< var glossary.simple-majority >}} vote of the {{< var acronyms.cab >}} may veto that candidate. This veto can be overruled by a {{< var glossary.supermajority >}} vote of the chapter. Failure for {{< var acronyms.cab >}} to meet with a candidate prior to elections will be interpreted as {{< var acronyms.cab >}} waiving their right to interview the candidate.
   a. Serves as a member of {{< var acronyms.ec >}}.
   a. Must live in the house.

1. Marshal
   a. Performs all duties stated in the {{< var acronyms.ibl >}} Article V, Section 6, paragraph f.
   a. Will submit a Marshal Plan as Temporary Legislation that expires at the end of the current semester for their office by the first chapter meeting of the semester of their term.
   a. Will reserve a location for initiation.
   a. Will organize a bid acceptance dinner and the bid acceptance ceremony.
   a. Serves as a member of {{< var acronyms.ec >}}.
   a. Must live in the house.

1. Scholarship Chair
   a. Performs all duties stated in the {{< var acronyms.ibl >}} Article V, Section 6, paragraph i.
   a. Performs all duties specified by the Greek Life Office, {{< var acronyms.ifc >}}, and the University.
   a. Will prepare a written scholarship program, submit it to the Office of Greek Life, and pass it as legislation in chapter by the 2nd chapter of their term, containing the following:\
      i. A plan for the creation of Scholarship contracts for all brothers.
      i. A plan for ensuring the chapter house is an environment conducive to studying.
      i. A plan for providing incentives for academic achievements.
   a. Will present the scholarship program to new members.
   a. Works with the Marshal to promote academic well-being among New Members.
   a. Organizes a formal scholarship dinner to recognize achievement about scholarship within the chapter.
   a. Will arrange at least one program per semester with a speaker who will talk to the chapter about scholarship or an issue relating to scholarship.
   a. Will ensure all brothers are part of at least one non-greek club or activity.
   a. {{< var glossary.attend >}}s monthly meetings with the Greek Community Educational Consultants in accordance with Case Western Reserve University ({{< var acronyms.cwru >}}) Greek {{< var glossary.community-standards >}}.
   a. Serves as a member of {{< var acronyms.ec >}}.
   a. Must live in the house.

1. Recruitment Chair
   a. Performs all duties stated in the {{< var acronyms.ibl >}} Article V, Section 6, paragraph l.
   a. Assumes responsibility for directing the recruitment process.
   a. Serves as Chair of the Recruitment Committee.
   a. Will run a recruitment workshop each semester.
   a. Will present a Rush calendar to the chapter by Initiation.
   a. Will be {{< var glossary.responsible >}} for any {{< var glossary.rush-period >}} that they have planned including those after their term.
   a. Confirms and tracks the attendance of each brother at Rush events (@sec-art-0ERS31Z3, Item 2). h. Serves as a member of {{< var acronyms.ec >}}.
   a. Must live in the house.

1. Chaplain
   a. Performs all duties stated in the {{< var acronyms.ibl >}} Article V, Section 6, paragraph g.
   a. Handles conflict resolution in the chapter.
   a. Organizes and mediates round table discussions on contentious issues between brothers.
   a. Brings elected officers up for standards for failing to perform the position's responsibilities and duties.
   a. Must live in the house.

1. Historian
   a. Performs all duties stated in the I{{< var acronyms.ibl >}}BL Article V, Section 6, paragraph h.
   a. Assists alumni relations chair with the alumni database.\
   a. Ensures that pictures are taken at chapter events.
   a. Will make a yearly scrapbook for the year that they serve, with assistance from the previous historian.
   a. Manages the chapter's online photo and video galleries jointly with the Public Relations Chair.
   a. Works with the house manager to ensure that composites are displayed correctly.
   a. Maintains and updates the photos around the house.
   a. Maintains the chapter museum.

1. First Guard
   a. Performs all duties stated in the {{< var acronyms.ibl >}} Article V, Section 6, paragraph j.
   a. Assists the Marshal in planning and executing initiation and prepares the chapter for it.
   a. Prepares the chapter room for meetings.
   a. Will enforce reasonable dress in the chapter room as stated in @sec-art-8XE7XCGC, Item 4.

1. Second Guard
   a. Performs all duties stated in the {{< var acronyms.ibl >}} Article V, Section 6, paragraph k.
   a. Assists the first guard in preparing the chapter room for meetings.

## Appointed Positions {#sec-art-QQ786XUW}

1. Executive Council Member at Large
   a. Must have previously served on {{< var acronyms.ec >}} for a full term.
   a. Must not hold another {{< var acronyms.ec >}} position.
   a. Assists and advises {{< var acronyms.ec >}}.

1. Public Relations Chair
   a. Serves as chair of the Public Relations Committee.
   a. Works with the Public Relations Committee to create PR for the public events of the chapter at the request of other chairs.
   a. Maintains the chapter social media pages and accounts.
   a. Serves as a member of {{< var acronyms.ccc >}}.

1. Social Chair
   a. Organizes {{< var glossary.social-event >}}s.
   a. Ensures that all {{< var glossary.social-event >}}s run in accordance with all University, Greek Life, {{< var acronyms.ifc >}}, North American Interfraternity Conference ({{< var acronyms.nic >}}), and {{< var acronyms.ihq >}} regulations and policies.
   a. Serves as chair of the Social Committee.
   a. Will {{< var glossary.attend >}} all {{< var acronyms.ifc >}} Social Chair meetings.
   a. Serves as a member of {{< var acronyms.ccc >}}.

1. Alumni Relations Chair\
   a. Collects materials for and edits the Alumni Newsletter with the help of the Alumni Corporation and sends out the Alumni newsletter before the last day of classes.
   a. Maintains the alumni database.
   a. Serves as chair of the Alumni Relations Committee.
   a. Organizes the Alumni Ceremony at the end of the semester in which they serve.
   a. Plans the annual OX Roast event with the alumni to be held in the fall semester.
   a. Will be appointed after OX Roast to serve until the next OX Roast.
   a. Serves as a member of {{< var acronyms.ccc >}}.

1. Membership Development Chair
   a. Serves as chair of the Membership Development Committee.
   a. Will plan and carry out at least one event or program in each of the following categories:
      i. Professional development
      i. Brotherhood development
      i. Recreation
   a. Serves as a member of {{< var acronyms.ccc >}}.

1. Philanthropy and Service Chair
   a. Serves as chair of the Philanthropy and Service Committee.
   a. Ensures the chapter meets the Greek Life goals for service and philanthropy.
   a. Informs the chapter of service and philanthropy opportunities.
   a. Serves as a member of {{< var acronyms.ccc >}}.

1. House Manager
   a. Will live in the house.
   a. Assumes responsibility for the maintenance of the fraternity residence and surrounding property.
   a. Oversees and assumes responsibility of the fraternity including repair and replacement of equipment.
   a. Creates, implements, and monitors a parking lot program to be approved by the treasurer.

1. Detail Manager
   a. Will pass a house and kitchen detail plan as legislation by the first chapter meeting of the semester in which they serve. The plan must contain provisions for the assessment of fines for delinquency in details.
   a. Assigns weekly house details and weekly kitchen details.
   a. Will be {{< var glossary.responsible >}} for the direction of all {{< var glossary.special-event-detail >}}s, which may be called at their discretion.

1. Food Steward
   a. Works with a chef or catering service to maintain a brotherhood meal plan.\
   a. Ensures the service chosen for the meal plan is paid for according to the agreement with the chef or catering service.
   a. Must be on the meal plan.
   a. Works with the Detail Manager to keep public areas in the kitchen clean and ensure proper storage of food.
   a. Assigns cabinet and fridge space to in-house brothers.
   a. Must live in the house.

1. Community Standards Chair
   a. Works with respective positions to ensure {{< var glossary.community-standards >}} are completed by the fall deadline.

1. Risk Manager
   a. Schedules Students Meeting About Risk and Responsibility Training ({{< var acronyms.smarrt >}}) or similar presentations at the request of the Greek Life Office.
   a. Ensures compliance with all Greek Life, University, {{< var acronyms.ihq >}}, and {{< var acronyms.nic >}} guidelines and policies.
   a. {{< var glossary.attend >}}s Office of Greek Life risk manager meetings.

1. Diversity, Equity, and Inclusion Chair
   a. {{< var glossary.attend >}}s all Diversity, Equity, and Inclusion roundtables hosted by the Greek Life Office. 13. Greek Games Chair
   a. Organizes the chapter's participation in Greek Week.
   a. {{< var glossary.attend >}}s Greek Week Chair meetings sponsored by the Greek Week Steering Committee. c. Appoints brothers to captain Greek Week events.

1. Interfraternity Congress Representative
   a. Represents the chapter at {{< var acronyms.ifc >}} meetings.
   a. Must have been a brother for at least one full semester.

1. Librarian
   a. Sits on the Scholarship Committee.
   a. Manages house library and book collections.

1. Standards Board At-Large Member
   a. Hears and rules on all cases brought before Standards Board as defined in @sec-art-IHXJUPV0.
   a. {{< var glossary.attend >}}s all meetings of Standards Board.
   a. Keeps confidential all matters related to judicial proceedings.
   a. Treats all brothers and New Members fairly, impartially, and consistently.

1. Temporary Chairs
   a. May be appointed by the President to be in charge of specific events. Examples include Damage Chair, Formal Chair, and Master of the Universe.

## Executive Council {#sec-art-D3IM05AX}

1. Membership
   a. {{< var acronyms.ec >}} will be composed of the following:
      i. President
      i. Vice President
      i. Vice President of Health and Safety
      i. Secretary
      i. Treasurer
      i. Marshal
      i. Scholarship Chair
      i. Recruitment Chair
      i. Executive Council Member at Large

1. Purpose, Duties, and Powers
   a. Interprets the bylaws as outlined in @sec-art-EXPT5HOU.
   a. Serves as an executive body.
   a. Guides the chapter in emergencies.
   a. Reviews excuses for chapter meetings and other chapter events.
      i. In evaluating excuses, the {{< var acronyms.ec >}} shall adhere to the standards set in the Acceptable Excuses Plan. The Acceptable Excuses Plan shall consist of the following:
         1. Specifically what is an acceptable excuse, with examples.
         1. Specifically what is not an acceptable excuse, with examples.
         1. The number of unexcused absences, missed chapters, and other mandatory events that are allowed per semester before being taken to standards board.
      i. The Acceptable Excuses Plan shall be distributed to the chapter one week before retreat at the beginning of every semester and approved at retreat, with any necessary amendments, as a piece of temporary legislation valid for one semester.
   a. Reviews Requests for {{< var glossary.deferment >}} (@sec-art-OUD16M61).
   a. Passes {{< var glossary.executive-edict >}}s as defined in @sec-art-9HMJ9WUB, Item 4.
   a. Suspends portions of the Bylaws subject to chapter approval as defined in @sec-art-JKVV6S2J.
   a. Reviews appeals to {{< var glossary.academic-probation >}} as defined in @sec-art-1UWTGO5I.
   a. Meets with respective {{< var acronyms.cab >}} member once a month.
   a. Appoints appointed positions.

1. Voting
   a. Voting Members
      i. Vice President
      i. Vice President of Health and Safety\
      i. Secretary
      i. Treasurer
      i. Marshal
      i. Recruitment Chair
      i. Scholarship Chair
   a. {{< var glossary.quorum >}} will consist of at least five members, at least four of whom must be voting members. c. All votes are decided by an {{< var glossary.absolute-majority >}} of {{< var acronyms.ec >}}.
      i. The President will have a vote in case of a tie.

1. Procedure
   a. {{< var acronyms.ec >}} is chaired by the Vice President.
   a. {{< var acronyms.ec >}} will meet weekly while school is in session.
   a. {{< var acronyms.ec >}} will admit any brother or candidate unless the meeting is declared closed by the Vice President or an {{< var glossary.absolute-majority >}} of {{< var acronyms.ec >}}.
      i. {{< var acronyms.ec >}} may admit any guest to closed {{< var acronyms.ec >}} by an {{< var glossary.absolute-majority >}} vote.
      i. {{< var acronyms.ec >}} meetings will be closed to non-{{< var acronyms.ec >}} members in situations that require discussing private or emergency matters such as Requests for {{< var glossary.deferment >}}.
   a. The Vice President will serve as the representative of {{< var acronyms.ec >}} to the chapter.

## Committees {#sec-art-VI2T9PVL}

1. The chapter will have the following groups of committees:
   a. Standard Committees
      i. Each Standard committee is part of a committee pair. The list of committees and committee pairs is as follows:
         1. Alumni Relations Committee and Member Development Committee
         1. Health and Safety Committee and Scholarship Committee
         1. Philanthropy and Service Committee and Social Committee
         1. Public Relations Committee and Recruitment Committee
      i. All Standard committees will do the following:
         1. Meet at least once every two weeks as directed by their chair.
            a. In direct exception to the previous bylaw, the Alumni Relations Committee and Member Development Committee only need to meet at least once every four weeks as directed by their chair.
         1. Assist the chair in the discharge of their duties.
         1. Create a set of goals for the committee at the first meeting of the committee.
         1. Work toward the goals of the committee.
   b. Operational Committees\
      i. Ad hoc committees
         1. The Vice President has the power to make other committees at their discretion.
      i. Budget Committee
         1. Purpose and Duties
            a. To create a budget for the chapter for the next year pursuant to @sec-art-GD7C1K2U.
            a. To examine any financial issues of the chapter.
         1. Membership
            a. The Treasurer will serve as chair of the Budget Committee.
            a. The body of the committee will be selected by the Treasurer.
         1. Procedure
            a. The committee will be created and convened during the budgeting process outlined in @sec-art-GD7C1K2U, Item 3.
            a. The committee may meet at other times to examine the finances of the chapter at the direction of {{< var acronyms.ec >}}.
      i. Committee Chair Committee ({{< var acronyms.ccc >}})
         1. Purpose
            a. To facilitate communication between committee chairs.
            a. To keep the Vice President informed of committee business.
            a. To help the Vice President ensure that committees are performing all necessary duties.
         1. Membership
            a. The Vice President will serve as the chair of {{< var acronyms.ccc >}}.
            a. The chairs of all Standard Committees will be members.
            a. Other brothers may be added to {{< var acronyms.ccc >}} at the Vice President's discretion.
         1. Procedure
            a. The committee will meet at least once every two weeks while school is in session.
            a. The Vice President will evaluate progress toward committee goals.
      i. Mandatory Bylaw Revision Committee
         1. The Mandatory Bylaw Revision Committee will function in accordance with @sec-art-YOSPIQLS.

1. Every brother must be a member of both of the Standard Committees that belong to the same committee pair.
   a. Brothers that serve as chairs of one Standard Committee must also be on the other Standard Committee in the committee pair.
   a. Brothers may choose to join other committees at their own discretion.
   a. If a brother misses two meetings of any one of their assigned committees without obtaining an approved excuse from that committee's chair, that committee's chair may bring that brother up for standards for behavior unbecoming of a brother.
   a. Committee meetings scheduled less than five days in advance cannot be counted towards the absences above.
