# Legislation {#sec-art-7452KYZC}

## Precedence {#sec-art-V4H7S16N}

1. The legislation of this chapter will be superseded by the Theta Chi International Bylaws ({{< var acronyms.ibl >}}), Theta Chi International Legislation, legislation passed by the Grand Chapter of Theta Chi Fraternity, and the Beta Nu of Theta Chi Local Bylaws.

## Categories and Duration {#sec-art-9HMJ9WUB}

1. Temporary Legislation:
   a. Must be passed by a {{< var glossary.simple-majority >}} vote.
   a. Expires one year from the date of passage unless a date of expiration is specified.

1. Permanent Legislation:
   a. Must be passed by a {{< var glossary.simple-majority >}} vote.
   a. Remains in effect indefinitely, until revoked or amended as specified below.

1. Emergency Legislation:
   a. Can be passed by a {{< var glossary.simple-majority >}} of those present (even if {{< var glossary.quorum >}} is not present).
   a. At the next chapter meeting where {{< var glossary.quorum >}} is present, the Vice President will bring the emergency legislation before the chapter as permanent or temporary legislation.

1. Executive Edicts:
   a. Must be approved by an {{< var glossary.absolute-majority >}} vote of Executive Council ({{< var acronyms.ec >}}), which immediately puts the edict into effect as legislation.
      i. At the next chapter meeting at which {{< var glossary.quorum >}} is present, the Vice President will bring the edict before the chapter as permanent or temporary legislation. The chapter must then approve the legislation for the edict to remain in effect.
   a. Supersedes all previous legislation.

1. If the legislation is not proposed as one of the above types, it will be treated as temporary legislation.

## Revoking or Amending {#sec-art-91S4OLEZ}

1. The legislation of this chapter may be revoked or amended by a {{< var glossary.simple-majority >}} vote.
1. No legislation can be revoked or amended if {{< var glossary.quorum >}} is not present with the exception of Emergency Legislation.
