# Appendix B

## Standards Rulings

1. September 25, 2010

   Charges: A brother was under a 2.2 {{< var acronyms.gpa >}} for two consecutive semesters.

   Plea: Responsible.

   Sanctions: Recommendation for suspension, voting privileges suspended until off of {{< var glossary.academic-probation >}}.

1. September 25, 2010

   Charges: A brother was under a 2.2 {{< var acronyms.gpa >}} for two consecutive semesters. Brother was currently on co-op.

   Plea: No Contest.

   Sanctions: Recommendation for suspension, voting privileges revoked upon return from co-op.

1. October 22, 2010

   Charges: A brother was living outside of the house without permission from the chapter. Plea: No Contest.

   Sanctions: Formal apology in chapter, {{< var glossary.staggard >}} for time equal to time out of the house upon return to the house. Recommendation for suspension.

1. February 7, 2012

   Charges: A brother was brought up for conduct unbecoming.

   Plea: Not Responsible.

   Sanctions: Letter of formal apology to those offended, immediate removal from office of Standards Board Justice.

1. January 11, 2015

   Charges: A brother was living outside of the house without permission from the chapter. Plea: No Contest.

   Sanctions: The brother must pay the difference between cost to live in the house and his rent, loss of voting rights, and required to still do house and kitchen details.

1. March 21, 2015

   Charges: Four brothers were planning to live outside of the house without permission from the chapter.

   Plea: No Contest.

   Sanctions: The brothers must remain on the house detail plan, maintain contact with the Scholarship Chair, and their voting rights were revoked.

1. April 26, 2015

   Charges: A brother was planning to live outside of the house without permission from the chapter. Plea: No Contest.

   Sanctions: The brother must complete kitchen details or actively {{< var glossary.attend >}} study tables at a rate set by the Scholarship Chair.

1. February 28, 2016

   Charges: A brother was planning on living outside the house without permission of the chapter.

   Plea: Not Responsible.

   Sanctions: No repercussions.

1. November 28, 2023

   Charges: A brother was planning on living outside the house without permission from the chapter. Plea: No Contest.

   Sanctions: No sanctions imposed, but if no medical exemption was obtained by the start of the following semester, the brother would be recommended for suspension.

1. November 28, 2023

   Charges: A brother was brought up for conduct unbecoming, specifically as it related to attendance and excuses surrounding chapter, as well as dismissive language used when this issue was trying to be resolved.

   Plea: Not Resonsible.

   Sanctions: The brother was told that they should be in chapter more, and that they should create a plan with the Scholarship Chair to ensure they would be in chapter more the next semester. {{< var acronyms.ec >}} was asked to make a clearer excuse plan that also answered the questions "what constitutes an excuse?" and "what constitutes full attendance at chapter?" in order to prevent future communication issues. For this trial, sanctions were given to the accused and a request was made to {{< var acronyms.ec >}}.
