# A: EC Interpretations {#sec-art-BW7GLKA5}

1. Academic warning is treated the same way as {{< var glossary.academic-probation >}} when a brother has not had classes for a semester.
1. Standards Board does NOT need to automatically recommend a brother for suspension if said brother is brought up for standards with the possibility of suspension.
1. When adding interpretations, make sure to reference the particular bylaw being interpreted and the year the interpretation was made.
1. Nov 02, 2025

   A brother who has been suspended cannot be present at any event with any sort of official restriction on individuals present. Such events include, but are not limited to, mixers, rush events, chapter, and any ritual ceremony.

   A suspended brother, should they be present at an event open to the public in the capacity of a member of the public should be expected to act as a member of the public. As such, they may be asked to leave at any time, for any reason, by a member of EC or the event lead. Such a suspended brother should not and cannot represent Theta Chi in any capacity. 
