project:
  type: book
book:
  title: "Beta Nu of Theta Chi Local Bylaws"
  author: ""
  date: "2025-02-14"
  chapters:
    - index.qmd
    - part: "Articles"
      chapters:
        - articles/article1.qmd
        - articles/article2.qmd
        - articles/article3.qmd
        - articles/article4.qmd
        - articles/article5.qmd
        - articles/article6.qmd
        - articles/article7.qmd
        - articles/article8.qmd
        - articles/article9.qmd
        - articles/article10.qmd
        - articles/article11.qmd
        - articles/article12.qmd
        - articles/article13.qmd
        - articles/article14.qmd
    - part: "Appendices"
      chapters:
        - appendices/appendix1.qmd
        - appendices/appendix2.qmd
        - appendices/appendix3.qmd
    - glossary.qmd
    - references.qmd
bibliography: references.bib
brand:
  light: brand_light.yml
  dark: brand_dark.yml
nocite: |
  @*
extensions:
  - extensions/article-ref
format:
  html:
    theme-default: dark
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{enumitem}
        \setlistdepth{10}
        \renewlist{itemize}{itemize}{10}
        \renewlist{enumerate}{enumerate}{10}

    template-partials:
      - before-body.tex

    keep-tex: true
