# Glossary

## Absolute Majority {#sec-absolute-majority}

A vote of strictly greater than ½ of the entire voting body, counting all brothers, including those not present and including those without voting rights.

## Absolute Supermajority {#sec-absolute-supermajority}

A vote of strictly greater than ⅔ of the entire voting body, counting all brothers, including those not present and including those without voting rights.

## Academic Probation {#sec-academic-probation}

See Article X, Section A, Item 2b. This is a restorative measure, not a punitive measure.

## Attend {#sec-attend}

A brother attends an event if he fulfills the attendance requirements for that event. Attendance requirements are defined at the discretion of the organizer of the event, with a suggested attendance portion being ¾ of the event's total run time.

## Ballot {#sec-ballot}

A secret vote as defined in Article IV, Section B, Item 2.

## Chapter Advisor {#sec-chapter-advisor}

For the purposes of these bylaws, a Chapter Advisor is any alumnus member of the chapter who serves on the Chapter Advisory Board (CAB).

## Community Standards {#sec-community-standards}

The list of requirements set forth by the Greek Life Office at Case Western Reserve University (CWRU) which is to be completed every calendar year, due finally in December.

## Deferment {#sec-deferment}

A payment plan approved by Executive Council (EC) based on a request for deferment and the recommendations of the Treasurer for a brother's debt.

## Executive Edict {#sec-executive-edict}

Legislation implemented in a time of emergency by a supermajority vote of EC. See Article II, Section B, Item 4.

## Financial Probation {#sec-financial-probation}

See Article VI, Section E, Item 3.

## Grade Improvement Plan {#sec-grade-improvement-plan}

A plan made by a brother on Academic Probation with help from the Scholarship Chair to improve his grades.

## Grievance {#sec-grievance}

A request submitted to EC for clarification of the intention of the bylaws. See Article I, Section D, Item 2.

## Informal Dress {#sec-informal-dress}

Any attire that would be reasonably agreed upon to be non-offensive. This consists of, at the very least, socks or closed-toes shoes, a shirt or upper body covering of some kind, and short/pants or a lower body covering of some kind. Shirts with graphics on them are acceptable only insofar as the graphics on them are acceptable. When in doubt, the chair of the current meeting has sole discretion over what is permissible unless stated otherwise in the bylaws or other rules governing the meeting.

## No Contest Plea {#sec-no-contest-plea}

The Accused attests to the truth of the accusation, but believes there are mitigating circumstances surrounding the accusation which exculpate him.

## Not Responsible {#sec-not-responsible}

A ruling that states that the Accused is not culpable for the accusation against him.

## Not Responsible Plea {#sec-not-responsible-plea}

The Accused denies culpability for the accusation.

## Official Chapter Event {#sec-official-chapter-event}

An event that all brothers must attend.

## Plurality {#sec-plurality}

The number of votes cast for a candidate who receives more than any other (this does not necessarily require an absolute majority).

## Probation {#sec-probation}

A brother on probation cannot attend social events and loses his voting rights.

## Quorum {#sec-quorum}

One more than half of the active chapter or the body described.

## Request for Deferment {#sec-request-for-deferment}

A form that includes how much money a brother wishes to defer, the reason a deferment is needed, and a payment plan for the amount deferred.

## Responsible {#sec-responsible}

A ruling that states that the Accused is culpable for the accusation against him.

## Responsible Plea {#sec-responsible-plea}

The Accused admits that he is rightfully accused and agrees to all sanctions given.

## Roster Number {#sec-roster-number}

For the purposes of these bylaws, a brother's roster number starts as the median of the actual roster numbers of his New Member Class.

## Rush Period {#sec-rush-period}

The period of time starting at the beginning of a fall or spring academic semester and ending at the end of the pledging ceremony that same semester.

## Safety Margin {#sec-safety-margin}

A sum of money built into the budget for the chapter which is set aside in case of unexpected expenses. **Scholarship Plan**\
The semesterly legislation created by the Scholarship Chair which is to include scholarship goals for the chapter and means of reaching those goals.

## Simple Majority {#sec-simple-majority}

A vote that, in order to succeed, requires affirmative votes from strictly more than ½ of brothers present and eligible to vote, provided a quorum is present.

## Social Event {#sec-social-event}

Open and closed parties sponsored by the fraternity and any other event given this designation by EC excluding house meals and Rush events. Examples: Mixers, some Greek Week Events, and Formals.

## Special Event Detail {#sec-special-event-detail}

An official chapter event declared by the Detail Manager with a stated objective such as cleaning the house before inspections or a Rush event. The chapter must be given at least twenty-four hours notice of such a session and excuses for the session will be approved by EC.

## Squatter's Rights {#sec-squatter-rights}

The second highest priority given to a brother when deciding housing assignments. A brother has squatter's rights for a room if he is living in that room during the semester in which room assignments are made.

## Staggard {#sec-staggard}

A brother who is staggard loses squatter's rights and has 100 added to his roster number. This effect stacks with itself.

## Supermajority {#sec-supermajority}

A vote that, in order to succeed, requires affirmative votes from strictly more than ⅔ of brothers present and eligible to vote, provided a quorum is present.

# Acronyms

## CAB {#sec-CAB}

Chapter Advisory Board

## CCC {#sec-CCC}

Committee Chair Committee

## CWRU {#sec-CWRU}

Case Western Reserve University

## EC {#sec-EC}

Executive Council

## GPA {#sec-GPA}

Grade Point Average

## IBL {#sec-IBL}

International Bylaws

## IFC {#sec-IFC}

Interfraternity Congress

## IHQ {#sec-IHQ}

International Headquarters

## NIC {#sec-NIC}

North American Interfraternity Conference

## SMARRT {#sec-SMARRT}

Students Meeting About Risk and Responsibility Training
